repos:
  - repo: local
    hooks:
      - id: increment-version
        name: Increment version in pyproject.toml
        entry: python3 scripts/increment_version.py
        language: system
        stages: [commit-msg]